services:
  local-mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: viggig
      MONGO_INITDB_ROOT_PASSWORD: compose
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
